### PR TITLE
Update to v1.1.2

### PR DESCRIPTION
**Pull request by xylar**
Remove local copy of license and example test (not needed).

Update tests to try out all examples.

Update import tests to make sure evtk works in addition to pyevtk

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by renefritze** [comment]
We could actually just run `pytest` now instead of all the examples manually

**Comment by xylar** [comment]
That sounds good.  I'll try it out locally and update.

CI isn't able to import `evtk.hl`, so I'm going to see what that's about.

**Comment by xylar** [comment]
Regarding `evtk.hl`, I just misunderstood the changes that were made.  I thought `evtk` would point to `pyevtk`.

**Comment by xylar** [comment]
@renefritze, I think it's just a bot glitch that travis-ci and appveyor are running.  I think this is safe to merge now that circleci and azure has run successfully.

I've asked the conda-forge folks on gitter what the deal might be: https://gitter.im/conda-forge/conda-forge.github.io

**Comment by renefritze** [comment]
So I guess we'll sit tight for a little while unless that's resolved, else merge nevertheless?

BTW, do you know what me must do so you can merge this yourself, @xylar ?

**Comment by xylar** [comment]
I would go ahead and merge.  I think they're resetting the bot but the actual packages are built by circleci (or maybe azure if plans have already changed) but definitely not travis or appveyor.  So we should get updated packages as long as circleci finished.

> BTW, do you know what me must do so you can merge this yourself, @xylar ?

I added myself as a maintainer.  As soon as you merge this PR, I'll be able to merge future PRs.

**Comment by xylar** [comment]
By the way, I have no experience with PyPI so I'll leave that update to you if that's okay.

**Comment by renefritze** [comment]
> I added myself as a maintainer. As soon as you merge this PR, I'll be able to merge future PRs.

Ah, great!

> By the way, I have no experience with PyPI so I'll leave that update to you if that's okay.

@somada141 is actually the only registered maintainer with push access to the PyPi project atm. Maybe we should change that too. Also it's pretty easy to automate to upload a whl from git-tag build from travis.ci

**Comment by somada141** [comment]
@renefritze @xylar please give me your PyPI usernames so I can add you as maintainers. I don't see a way to create non-user-specific keys for PyPI so it seems we'd have to use actual user creds to upload to PyPI unless you guys are familiar with an alternative approach.

**Comment by xylar** [comment]
@somada141, I just created an account with username `xylar` on `pypi`.  Let me know if you need anything else from me.

**Comment by renefritze** [comment]
It's "koshi" for me. And no, there's no auth tokens to generate or anything towards that. They're pretty backwards with that.

**Comment by somada141** [comment]
@xylar @renefritze I've just added you both as maintainers. Is that sufficient or would you like me to make one of you owners?

**Comment by renefritze** [comment]
It might be nice if I was owner so I could delete something like accidental uploads. IIRC maintainers cannot do that. Thanks!

**Comment by somada141** [comment]
Didn't realise we could all be owners. All three of us now are :)

**Pull request merged**
